version: '2'

services:
    web:
        image: 3dsinteractive/nginx:1.12
        depends_on:
            - phpfpm
            - mysql
        ports:
            - 80:8080
            - 443:8443
        volumes:
            - ./app:/app
            - ./dockers/web/logs:/opt/bitnami/nginx/logs
            - ./dockers/web/nginx:/bitnami/nginx
            - ./dockers/certs:/bitnami/nginx/conf/bitnami/certs
    phpfpm:
        image: 3dsinteractive/php-fpm:7.1
        depends_on:
            - mysql
        volumes:
            - ./app:/app
            - ./dockers/phpfpm:/bitnami/php-fpm
    mysql:
        image: 3dsinteractive/mysql:5.7.19
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=my_user
            - MYSQL_PASSWORD=my_password
            - MYSQL_DATABASE=my_database
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            - MYSQL_USERNAME=my_user
            - PMA_HOST=mysql
        ports:
            - 8888:80
    tool:
        build: dockers/tool
        tty: true